- name: Update APT cache (initial)
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    force_apt_get: true
  become: true
  become_method: sudo
  register: apt_update
  retries: 5
  delay: 10
  until: apt_update is success

- name: Upgrade all packages
  ansible.builtin.apt:
    upgrade: dist
    force_apt_get: true
  become: true
  become_method: sudo

- name: Remove unofficial Docker packages
  ansible.builtin.package:
    name:
      - docker.io
      - docker-compose
      - docker-doc
      - podman-docker
    state: absent
  register: docker_remove
  become: true
  become_method: sudo

- name: Remove NetExec (use pipx instead)
  ansible.builtin.package:
    name: netexec
    state: absent
  become: true
  become_method: sudo

- name: Remove Containerd/Runc
  ansible.builtin.package:
    name:
      - containerd
      - runc
    state: absent
  when: docker_remove.changed
  become: true
  become_method: sudo

- name: Install prerequisite packages
  ansible.builtin.apt:
    name:
      - jq
      - pipx
      - ntpsec-ntpdate
      - flameshot
      - exiftool
      - rsyslog
      - ca-certificates
      - curl
      - gh
    state: latest
    update_cache: true
  become: true
  become_method: sudo

- name: Ensure /etc/apt/keyrings directory exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  become: true
  become_method: sudo

- name: Add Docker GPG key
  ansible.builtin.get_url:
    url: "https://download.docker.com/linux/debian/gpg"
    dest: "/etc/apt/keyrings/docker.gpg"
    mode: '0644'
    force: true
  become: true
  become_method: sudo

- name: Add Docker GPG key
  ansible.builtin.get_url:
    url: "https://download.docker.com/linux/debian/gpg"
    dest: "/etc/apt/keyrings/docker.gpg"
    mode: '0644'
    force: true
  become: true
  become_method: sudo

- name: Add Docker APT repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian {{ distribution }} stable"
    state: present
    filename: docker
    update_cache: true
  become: true
  become_method: sudo

- name: Update APT cache (post-repository)
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    force_apt_get: true
  become: true
  become_method: sudo
  register: apt_update
  retries: 5
  delay: 10
  until: apt_update is success

- name: Install Docker packages
  ansible.builtin.package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: latest
  become: true
  become_method: sudo
