---
- name: "Kali Setup"
  hosts: localhost
  connection: local
  tasks:
    - name: "Demo Debug"
      debug:
        msg: "Please Subscribe"
  roles:
    - role: "roles/customize-browser"
    - role: "roles/desktop-setup"
