---
- name: "Kali Setup"
  hosts: localhost
  connection: local
  roles:
    - role: "roles/install-tools"
    - role: "roles/desktop-setup"
    - role: "roles/customize-browser"
    - role: gantsign.visual-studio-code
      users:
        - username: "{{ ansible_user_id }}"
          visual_studio_code_extensions:
            - streetsidesoftware.code-spell-checker
            - ms-python.python
            - GitHub.copilot
            - snyk-security.snyk-vulnerability-scanner
